\definecolor{fancyTextColor}{HTML}{4284f5}

# Linear Equations in Linear Algebra

## Systems of Linear Equations

### Linear System, Coefficient and Variable 

A linear equation is 
\begin{equation}
    a_1x_1+a_2x_2+\cdots+a_nx_n=b \qquad n=1, 2, 3, \cdots, \infty
\end{equation}
$a_1,\dots,a_n$ are real or complex numbers, called **coefficient**.\
$x_1,\dots,x_n$ are unknown **variables**.\
A system of linear equations is called **linear system**.\

### Solution of a linear system

A system of linear equations has

\begin{enumerate}
\item no solution
\item exactly one solution
\item infinitely many solutions
\end{enumerate}
The set of all possible solution is called **solution set** .\
Linear systems with the same solution set are called **equivalent**.\
A system of linear equations is said to be **consistent** if it has either one solution or
infinitely many solutions\
A system is **inconsistent** if it has no solution.


### Matrix Notation

Suppose we have a linear system:

\begin{equation}
\begin{aligned}
&x_1-2x_2+x_3=0\\
&2x_2-8x_3=8\\
&5x_1-5x_3=10
\end{aligned}
\end{equation}

Here, we introduce two forms to represent a linear system using matrix.\

#### Augmented Matrix Form

\begin{equation}
\begin{aligned}
M= \begin{bmatrix}
1 & -2 & 1 & 0\\
0 & 2 & -8 & 8\\
5 & 0 & -5 & 10
\end{bmatrix}\\
%&\xrightarrow[R_1-5R_3]{R_2+2R_3}
\end{aligned}
\end{equation}

#### Coefficient Matrix Form

Denote

\begin{equation}
    \begin{aligned}
A=    \begin{bmatrix}
1 & -2 & 1 \\
0 & 2 & -8 \\
5 & 0 & -5 
\end{bmatrix} \qquad X=\begin{bmatrix}
x_1\\ x_2\\x_3
\end{bmatrix} \qquad B=\begin{bmatrix}
0 \\ 8 \\ 10
\end{bmatrix} \qquad \iff \quad  AX=B \\
    \end{aligned}
\end{equation}

#### Matrix Elements

\begin{equation}
\begin{aligned}
&M= \begin{bmatrix}
1 & -2 & 1 & 0\\
0 & 2 & -8 & 8\\
5 & 0 & -5 & 10
\end{bmatrix}\quad  \Rightarrow \quad M= \begin{bmatrix}
m_{11} & m_{12} & m_{13} & m_{14}\\
m_{21} & m_{22} & m_{23} & m_{24}\\
m_{31} & m_{32} & m_{33} & m_{34}
\end{bmatrix}\\\\
& \text{$M$ is a 3 $\times$ 4 matrix (3 rows, 4 columns)} 
%&\xrightarrow[R_1-5R_3]{R_2+2R_3} 
\end{aligned}
\end{equation}

The form of $AX=B$ is based on the matrix multiplication, which we are going further in next chapter.\



### Elementary Row Operations

+ (Replacement, 倍加变换) Replace one row by the sum of itself and a multiple of another row.
+ (Interchange, 对换变换) Interchange two rows.
+ (Scaling, 倍乘变换) Multiply all entries in a row by a nonzero constant.


Two matrices are called row **equivalent** if there is a sequence of elementary row operations that transforms one matrix into the other.\
It is important to note that row operations are **reversible**.\
If the augmented matrices of two linear systems are row equivalent, then the two systems have the same solution set.\

### Existence and Uniqueness of Solutions

Two fundamental questions about a linear system are as follows:

+ Is the system consistent; that is, does at least one solution exist?
+ If a solution exists, is it the only one; that is, is the solution unique?

## Row Reduction and Echelon Form

### Leading Entry and Pivot Position

\begin{equation}
\begin{bmatrix}
{1} & -2 & 1 & 0\\
0 & {2} & -8 & 8\\
{5} & 0 & -5 & 10\\
\end{bmatrix}\\
\end{equation}

A **leading entry** of a row refers to the leftmost nonzero entry (in a nonzero row).\

::: {.theorem}
This is a `theorem` environment that can contain **any**
_Markdown_ syntax.
:::
